title: [Virtual Data Container]
description: [A new way of visualising Data and offering them as products & services]
theme: jekyll-theme-leap-day
logo: https://github.com/thevdc/virtualdatacontainer/blob/master/VDC-logo.png
