theme: jekyll-theme-hacker
logo: https://github.com/thevdc/virtualdatacontainer/blob/master/VDC-logo.png
title: VDC
description: Virtual Data Container - A new way of visualising Data and offering them as products & services
